const express=require('express');const prisma=require('../db');const {authenticate}=require('../middleware/auth');
const router=express.Router();router.use(authenticate);
const out=e=>({...e,event_date:e.eventDate,event_time:e.eventTime,registration_url:e.registrationUrl});
router.get('/',async(req,res)=>{const rows=await prisma.event.findMany({where:{tenantId:req.tenantId},orderBy:{createdAt:'desc'}});const result=await Promise.all(rows.map(async e=>({...out(e),contactCount:await prisma.contact.count({where:{tenantId:req.tenantId,eventId:e.id}}),campaignCount:await prisma.campaign.count({where:{tenantId:req.tenantId,eventId:e.id}})})));res.json(result);});
router.get('/:id',async(req,res)=>{const e=await prisma.event.findFirst({where:{id:Number(req.params.id),tenantId:req.tenantId}});if(!e)return res.status(404).json({error:'Event not found.'});res.json(out(e));});
router.post('/',async(req,res)=>{const b=req.body||{};if(!b.name)return res.status(400).json({error:'Event name is required.'});const e=await prisma.event.create({data:{tenantId:req.tenantId,name:b.name,eventDate:b.event_date||null,eventTime:b.event_time||null,venue:b.venue||null,address:b.address||null,description:b.description||null,registrationUrl:b.registration_url||null,status:b.status||'upcoming'}});res.status(201).json(out(e));});
router.put('/:id',async(req,res)=>{const id=Number(req.params.id);const old=await prisma.event.findFirst({where:{id,tenantId:req.tenantId}});if(!old)return res.status(404).json({error:'Event not found.'});const b=req.body||{};const e=await prisma.event.update({where:{id},data:{name:b.name??old.name,eventDate:b.event_date??old.eventDate,eventTime:b.event_time??old.eventTime,venue:b.venue??old.venue,address:b.address??old.address,description:b.description??old.description,registrationUrl:b.registration_url??old.registrationUrl,status:b.status??old.status}});res.json(out(e));});
router.delete('/:id',async(req,res)=>{const e=await prisma.event.findFirst({where:{id:Number(req.params.id),tenantId:req.tenantId}});if(!e)return res.status(404).json({error:'Event not found.'});await prisma.event.delete({where:{id:e.id}});res.json({success:true});});
module.exports=router;
