const express=require('express');const crypto=require('crypto');const prisma=require('../db');const {authenticate,requireAdmin}=require('../middleware/auth');const {encrypt}=require('../services/crypto');const meta=require('../services/meta');const {broadcast}=require('../services/realtime');
const router=express.Router();

router.get('/webhook',async(req,res)=>{const mode=req.query['hub.mode'];const token=req.query['hub.verify_token'];const challenge=req.query['hub.challenge'];if(mode!=='subscribe'||!token)return res.sendStatus(400);const config=await prisma.whatsAppConfiguration.findFirst({where:{webhookVerifyToken:String(token)}});if(!config)return res.sendStatus(403);res.status(200).send(challenge);});

router.post('/webhook',express.raw({type:'application/json',limit:'2mb'}),async(req,res)=>{const raw=Buffer.isBuffer(req.body)?req.body.toString('utf8'):JSON.stringify(req.body||{});const signature=req.headers['x-hub-signature-256'];const appSecret=process.env.META_APP_SECRET||'';if(appSecret&&signature){const expected='sha256='+crypto.createHmac('sha256',appSecret).update(raw).digest('hex');if(signature.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))return res.sendStatus(401);}
try{const payload=JSON.parse(raw);const value=payload?.entry?.[0]?.changes?.[0]?.value;const phoneId=value?.metadata?.phone_number_id;const config=phoneId?await prisma.whatsAppConfiguration.findFirst({where:{phoneNumberId:String(phoneId)}}):await prisma.whatsAppConfiguration.findFirst();if(!config)return res.json({received:true});const tenantId=config.tenantId;const eventKey=crypto.createHash('sha256').update(raw).digest('hex');const existing=await prisma.webhookEvent.findUnique({where:{eventKey}});if(existing)return res.json({received:true,deduplicated:true});await prisma.webhookEvent.create({data:{tenantId,eventType:'whatsapp',eventKey,payload:payload,processed:true}});
for(const st of value?.statuses||[]){const m=await prisma.message.findFirst({where:{tenantId,metaMessageId:st.id}});if(!m)continue;const status=String(st.status||'').toLowerCase();const data=status==='sent'?{status:'sent',sentAt:new Date()}:status==='delivered'?{status:'delivered',deliveredAt:new Date()}:status==='read'?{status:'read',readAt:new Date()}:status==='failed'?{status:'failed',failedAt:new Date(),error:st.errors?.[0]?.title||'Meta delivery failed',metaErrorCode:st.errors?.[0]?.code?String(st.errors[0].code):null}:null;if(data){await prisma.message.update({where:{id:m.id},data});await prisma.messageStatusLog.create({data:{tenantId,messageId:m.id,status,rawPayload:st}});broadcast(tenantId,'message.status',{messageId:m.id,status});}}
for(const im of value?.messages||[]){const phone='+'+String(im.from||'').replace(/\D/g,'');const profile=value?.contacts?.find(x=>x.wa_id===im.from)?.profile?.name||phone;const contact=await prisma.contact.upsert({where:{tenantId_phone:{tenantId,phone}},update:{name:profile},create:{tenantId,name:profile,phone}});let conversation=await prisma.conversation.findUnique({where:{tenantId_phone:{tenantId,phone}}});if(!conversation)conversation=await prisma.conversation.create({data:{tenantId,contactId:contact.id,phone,contactName:profile,lastMessageAt:new Date(),status:'open'}});const body=im.text?.body||im.button?.text||im.interactive?.button_reply?.title||im.interactive?.list_reply?.title||`[${im.type||'message'}]`;const cm=await prisma.conversationMessage.create({data:{tenantId,conversationId:conversation.id,direction:'inbound',content:body,metaMessageId:im.id,status:'received'}});await prisma.conversation.update({where:{id:conversation.id},data:{lastMessageAt:new Date(),status:'open'}});broadcast(tenantId,'inbox.message',{conversationId:conversation.id,message:cm});}
res.json({received:true});}catch(e){console.error('Webhook processing error',e);res.status(200).json({received:true});}});
router.use(require('express').json({limit:'10mb'}));router.use(express.json({limit:'10mb'}));router.use(authenticate);
router.get('/config',async(req,res)=>{const c=await meta.getConfig(req.tenantId);if(!c)return res.json({mode:process.env.WHATSAPP_MODE||'mock',connection_status:'not_connected',has_access_token:false,webhook_verify_token:process.env.META_WEBHOOK_VERIFY_TOKEN||'change-me'});res.json({id:c.id,mode:c.mode,connection_status:c.connectionStatus,business_account_id:c.businessAccountId||'',phone_number_id:c.phoneNumberId||'',display_phone_number:c.displayPhoneNumber||'',webhook_verify_token:c.webhookVerifyToken||'',has_access_token:!!c.accessToken});});
router.put('/config',requireAdmin,async(req,res)=>{const b=req.body||{};const c=await prisma.whatsAppConfiguration.upsert({where:{tenantId:req.tenantId},update:{businessAccountId:b.business_account_id??b.waba_id??null,phoneNumberId:b.phone_number_id??null,displayPhoneNumber:b.display_phone_number??null,accessToken:b.access_token?encrypt(b.access_token):undefined,webhookVerifyToken:b.webhook_verify_token??undefined,connectionStatus:b.mode==='live'?'connected':'connected',mode:b.mode||'mock'},create:{tenantId:req.tenantId,businessAccountId:b.business_account_id??b.waba_id??null,phoneNumberId:b.phone_number_id??null,displayPhoneNumber:b.display_phone_number??null,accessToken:b.access_token?encrypt(b.access_token):null,webhookVerifyToken:b.webhook_verify_token||process.env.META_WEBHOOK_VERIFY_TOKEN||'change-me',connectionStatus:b.mode==='live'?'connected':'connected',mode:b.mode||'mock'}});res.json({...c,accessToken:undefined,access_token:undefined});});
router.post('/test',requireAdmin,async(req,res)=>{const to=req.body?.to;if(to){const r=await meta.sendTextMessage({tenantId:req.tenantId,to,body:req.body?.body||'Bharat CRM WhatsApp integration test'});return res.status(r.ok?200:502).json(r);}const c=await meta.getConfig(req.tenantId);if((c?.mode||process.env.WHATSAPP_MODE||'mock')==='mock')return res.json({ok:true,mock:true,message:'Mock WhatsApp connection is ready. No real message was sent.'});if(!c?.accessToken||!c?.phoneNumberId)return res.status(400).json({ok:false,error:'Configure Business Account ID, Phone Number ID and Meta access token first.'});const r=await meta.sendTextMessage({tenantId:req.tenantId,to:req.body?.test_to||c.displayPhoneNumber,body:'Bharat CRM WhatsApp integration test'});res.status(r.ok?200:502).json({...r,message:r.ok?'Meta WhatsApp API accepted the test message.':r.error});});
router.post('/test-connection',requireAdmin,async(req,res)=>{const c=await meta.getConfig(req.tenantId);if((c?.mode||process.env.WHATSAPP_MODE||'mock')==='mock')return res.json({ok:true,message:'Mock WhatsApp connection is ready. No real message was sent.'});if(!c?.accessToken||!c?.phoneNumberId)return res.status(400).json({ok:false,error:'Configure Business Account ID, Phone Number ID and Meta access token first.'});const r=await meta.sendTextMessage({tenantId:req.tenantId,to:req.body?.to||c.displayPhoneNumber,body:'Bharat CRM connection test'});res.status(r.ok?200:502).json({ok:r.ok,message:r.ok?'Meta WhatsApp API accepted the test message.':(r.error||'Meta connection test failed.'),metaMessageId:r.metaMessageId||null});});
router.post('/sync-templates',requireAdmin,async(req,res)=>{const r=await meta.syncTemplates(req.tenantId);res.status(r.ok?200:502).json(r);});
module.exports=router;
